### ISSUE TITLE
Calculations for Motor Specifications

### ISSUE THREAD

**Issue by davidcartiel** [Integrated-Project-2-UVic-UCC/rubik-s-cube#17]

**Comment by marcsala27** [comment]
Calculations to know which motor do we need to move a face of the Rubik's cube.

[Calculations for Motor Specifications.pdf](https://github.com/Integrated-Project-2-UVic-UCC/rubik-s-cube/files/6590842/Calculations.for.Motor.Specifications.pdf)

[Calculations.and.results.Stepper.motor.pdf](https://github.com/Integrated-Project-2-UVic-UCC/rubik-s-cube/files/6271800/Calculations.and.results.Stepper.motor.pdf)

**Comment by josepmaria-carbonell** [comment]
@marcsala27   transform documents to pdf and attach them here, it is easier to reviewç

The calculations are very simple and need to be explained. You must improve them
