### ISSUE TITLE
Disseny peça d'encaix

### ISSUE THREAD

**Issue by davidcartiel** [Integrated-Project-2-UVic-UCC/rubik-s-cube#19]

**Comment by marcpujolar** [comment]
We have finished the center piece of the rubik cube with good results for us. What we were most concerned about was that the piece did not have tight enough.
![WhatsApp Image 2021-04-12 at 18 47 59](https://user-images.githubusercontent.com/79194484/114431870-4777ed00-9bc0-11eb-9fad-639258add589.jpeg)

![WhatsApp Image 2021-04-12 at 18 47 59 (1)](https://user-images.githubusercontent.com/79194484/114431832-3b8c2b00-9bc0-11eb-9a34-590c40a85922.jpeg)
