### ISSUE TITLE
Shopping List

### ISSUE THREAD

**Issue by davidcartiel** [Integrated-Project-2-UVic-UCC/rubik-s-cube#4]
- [x] Arduino Mega
- [x] 6 Nema17 4401
- [x] 6 Drivers A988
- [x] Filament impresora 3D PLA, 1,75mm 250g
- [x] Webcam

**Comment by marcpujolar** [comment]
We already have Arduino Mega, a Nema 17 and a Driver.

**Comment by davidcartiel** [comment]
All the components are saved in a locker in the laboratory of electronics.
