### ISSUE TITLE
Final presentation 07/06

### ISSUE THREAD

**Issue by davidcartiel** [Integrated-Project-2-UVic-UCC/rubik-s-cube#6]
Here we'll leave the pdf version of our Final Presentation.

**Comment by marcsala27** [comment]
[Final Presentation Rubik's Cube Solver.pdf](https://github.com/Integrated-Project-2-UVic-UCC/rubik-s-cube/files/6617882/Final.Presentation.Rubik.s.Cube.Solver.pdf)
