### ISSUE TITLE
Electric Circuit Design

### ISSUE THREAD

**Issue by davidcartiel** [Integrated-Project-2-UVic-UCC/rubik-s-cube#7]
This is the example we have followed to connect our stepper motor and the driver to the Arduino.
![image](https://user-images.githubusercontent.com/79194219/112187451-6824d680-8c02-11eb-969c-211477afe38c.png)

This image belongs to:
https://howtomechatronics.com/tutorials/arduino/how-to-control-stepper-motor-with-a4988-driver-and-arduino/

**Comment by marcsala27** [comment]
Here's the electric circuit design of the realistic components used:

<img width="408" alt="Electric Realistic Design RCS" src="https://user-images.githubusercontent.com/79104840/120630531-38e2df00-c467-11eb-8f43-04705b732705.PNG">

**Comment by marcsala27** [comment]
This is the electric scheme of all the connections and elements used in the electronical part:

<img width="398" alt="Electric Scheme RCS" src="https://user-images.githubusercontent.com/79104840/120630911-924b0e00-c467-11eb-9672-6e549b6ab48a.PNG">

**Comment by marcsala27** [comment]
The .fzz documents are in the web page. There you'll be able to know more details of the components and the connections.
