### ISSUE TITLE
3D Print

### ISSUE THREAD

**Issue by davidcartiel** [Integrated-Project-2-UVic-UCC/rubik-s-cube#8]
- [x] 6xLace Pieces
- [x] 1xLower Motor Axis

**Comment by davidcartiel** [comment]
Encaix Peces

We have printed some parts, that were incorrect and we have changed the filed we created to improve them.

**Comment by marcsala27** [comment]
- [x] 4xLateral Motor Axis
- [x] 1xSuperior Motor Axis
- [x] 1xMotor Tower

**Comment by marcsala27** [comment]
- [x] 4xMotor Tower
- [x] 1xMotor Bridge
